# SPDX-FileCopyrightText: 2023 C. J. Howard
# SPDX-License-Identifier: CC0-1.0

name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_platform: "windows"
            build_arch: "x64"
            build_gen: "Visual Studio 17 2022"
          # - os: ubuntu-latest
            # build_platform: "linux"
            # build_arch: "x64"
            # build_gen: "Unix Makefiles"
    
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    
    - name: CMake configure 
      run: cmake -B build -G "${{matrix.build_gen}}" -A "${{matrix.build_arch}}"
    
    - name: CMake build
      run: cmake --build build --config Release
