# SPDX-FileCopyrightText: 2023 C. J. Howard
# SPDX-License-Identifier: CC0-1.0

name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: ubuntu-latest
            # build_type: "Release"
            # build_gen: "Unix Makefiles"
          - os: windows-latest
            build_platform: "windows"
            build_arch: "x64"
            build_type: "Release"
            build_gen: "Visual Studio 17 2022"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: CMake configure 
      run: cmake -B build -G "${{matrix.build_gen}}"
    
    - name: CMake build
      run: cmake --build build --config Release
    
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.build_platform}}-${{matrix.build_arch}}-release
        path: |
          build/Release
