# SPDX-FileCopyrightText: 2023 C. J. Howard
# SPDX-License-Identifier: CC0-1.0

name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_type: "Release"
            build_gen: "Unix Makefiles"
          - os: windows-latest
            build_type: "Release"
            build_gen: "Visual Studio 17 2022"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: CMake configure 
      run: cmake -B ${{github.workspace}}/build -G "${{matrix.build_gen}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      
    - name: CMake build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
